--
-- PostgreSQL database dump
--

\restrict 5Ybf6SkUZOAsWXuUrgrXQLfipQZG59HXri3OHnyopQ2BoNfVenqM9jTJpGxOe3T

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Cargos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Cargos" (
    "CargoID" integer NOT NULL,
    "Description" text NOT NULL,
    "Weight" double precision NOT NULL,
    "IsHazardous" boolean NOT NULL,
    "Status" integer NOT NULL,
    "ServiceRequestID" integer NOT NULL
);


ALTER TABLE public."Cargos" OWNER TO postgres;

--
-- Name: Cargos_CargoID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Cargos" ALTER COLUMN "CargoID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cargos_CargoID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Documents" (
    "DocumentID" integer NOT NULL,
    "DocumentName" text NOT NULL,
    "FilePath" text NOT NULL,
    "IsVerified" boolean NOT NULL,
    "ServiceRequestID" integer NOT NULL
);


ALTER TABLE public."Documents" OWNER TO postgres;

--
-- Name: Documents_DocumentID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Documents" ALTER COLUMN "DocumentID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Documents_DocumentID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Invoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Invoices" (
    "InvoiceID" integer NOT NULL,
    "InvoiceNumber" text NOT NULL,
    "IssueDate" timestamp with time zone NOT NULL,
    "TotalAmount" double precision NOT NULL,
    "Status" integer NOT NULL,
    "ServiceRequestID" integer NOT NULL
);


ALTER TABLE public."Invoices" OWNER TO postgres;

--
-- Name: Invoices_InvoiceID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Invoices" ALTER COLUMN "InvoiceID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Invoices_InvoiceID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Payments" (
    "PaymentID" integer NOT NULL,
    "PaymentDate" timestamp with time zone NOT NULL,
    "Amount" double precision NOT NULL,
    "PaymentMethod" text NOT NULL,
    "InvoiceID" integer NOT NULL
);


ALTER TABLE public."Payments" OWNER TO postgres;

--
-- Name: Payments_PaymentID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Payments" ALTER COLUMN "PaymentID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Payments_PaymentID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Schedules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Schedules" (
    "ScheduleID" integer NOT NULL,
    "BerthNumber" integer NOT NULL,
    "ActualArrival" timestamp with time zone NOT NULL,
    "ActualDeparture" timestamp with time zone NOT NULL,
    "ServiceRequestID" integer NOT NULL
);


ALTER TABLE public."Schedules" OWNER TO postgres;

--
-- Name: Schedules_ScheduleID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Schedules" ALTER COLUMN "ScheduleID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Schedules_ScheduleID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ServiceRequests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ServiceRequests" (
    "RequestID" integer NOT NULL,
    "RequestDate" timestamp with time zone NOT NULL,
    "ServiceType" text NOT NULL,
    "Status" integer NOT NULL,
    "EstimatedArrival" timestamp with time zone NOT NULL,
    "VesselID" integer NOT NULL,
    "CreatedByUserID" integer NOT NULL
);


ALTER TABLE public."ServiceRequests" OWNER TO postgres;

--
-- Name: ServiceRequests_RequestID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ServiceRequests" ALTER COLUMN "RequestID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ServiceRequests_RequestID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "UserID" integer NOT NULL,
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" integer NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_UserID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "UserID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_UserID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Vessels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Vessels" (
    "VesselID" integer NOT NULL,
    "VesselName" text NOT NULL,
    "IMONumber" text NOT NULL,
    "Type" text NOT NULL,
    "Capacity" double precision NOT NULL
);


ALTER TABLE public."Vessels" OWNER TO postgres;

--
-- Name: Vessels_VesselID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Vessels" ALTER COLUMN "VesselID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Vessels_VesselID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Cargos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Cargos" ("CargoID", "Description", "Weight", "IsHazardous", "Status", "ServiceRequestID") FROM stdin;
\.


--
-- Data for Name: Documents; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Documents" ("DocumentID", "DocumentName", "FilePath", "IsVerified", "ServiceRequestID") FROM stdin;
\.


--
-- Data for Name: Invoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Invoices" ("InvoiceID", "InvoiceNumber", "IssueDate", "TotalAmount", "Status", "ServiceRequestID") FROM stdin;
\.


--
-- Data for Name: Payments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Payments" ("PaymentID", "PaymentDate", "Amount", "PaymentMethod", "InvoiceID") FROM stdin;
\.


--
-- Data for Name: Schedules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Schedules" ("ScheduleID", "BerthNumber", "ActualArrival", "ActualDeparture", "ServiceRequestID") FROM stdin;
\.


--
-- Data for Name: ServiceRequests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ServiceRequests" ("RequestID", "RequestDate", "ServiceType", "Status", "EstimatedArrival", "VesselID", "CreatedByUserID") FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("UserID", "Username", "PasswordHash", "Role") FROM stdin;
1	finance	$2a$11$M6xcToOCzvT8bl6ubfTSsOe5xzUIQYKG3h9gXuK./qxzwwPNdlPNu	3
2	manager	$2a$11$55P6W/ULtkB7evyXHYSEzuDcaaZbhcejewOBwAKRFCfsx0kI0sRgW	1
3	agent	$2a$11$uADXtdSSFW1yA59EeG6QNOEMSSxObl6FCUou5Mcp4wVTeCQgs44u2	0
\.


--
-- Data for Name: Vessels; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Vessels" ("VesselID", "VesselName", "IMONumber", "Type", "Capacity") FROM stdin;
\.


--
-- Name: Cargos_CargoID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Cargos_CargoID_seq"', 1, false);


--
-- Name: Documents_DocumentID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Documents_DocumentID_seq"', 1, false);


--
-- Name: Invoices_InvoiceID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Invoices_InvoiceID_seq"', 1, false);


--
-- Name: Payments_PaymentID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Payments_PaymentID_seq"', 1, false);


--
-- Name: Schedules_ScheduleID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Schedules_ScheduleID_seq"', 1, false);


--
-- Name: ServiceRequests_RequestID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ServiceRequests_RequestID_seq"', 1, false);


--
-- Name: Users_UserID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_UserID_seq"', 3, true);


--
-- Name: Vessels_VesselID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Vessels_VesselID_seq"', 1, false);


--
-- Name: Cargos PK_Cargos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cargos"
    ADD CONSTRAINT "PK_Cargos" PRIMARY KEY ("CargoID");


--
-- Name: Documents PK_Documents; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Documents"
    ADD CONSTRAINT "PK_Documents" PRIMARY KEY ("DocumentID");


--
-- Name: Invoices PK_Invoices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invoices"
    ADD CONSTRAINT "PK_Invoices" PRIMARY KEY ("InvoiceID");


--
-- Name: Payments PK_Payments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Payments"
    ADD CONSTRAINT "PK_Payments" PRIMARY KEY ("PaymentID");


--
-- Name: Schedules PK_Schedules; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Schedules"
    ADD CONSTRAINT "PK_Schedules" PRIMARY KEY ("ScheduleID");


--
-- Name: ServiceRequests PK_ServiceRequests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ServiceRequests"
    ADD CONSTRAINT "PK_ServiceRequests" PRIMARY KEY ("RequestID");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("UserID");


--
-- Name: Vessels PK_Vessels; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vessels"
    ADD CONSTRAINT "PK_Vessels" PRIMARY KEY ("VesselID");


--
-- Name: IX_Cargos_ServiceRequestID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Cargos_ServiceRequestID" ON public."Cargos" USING btree ("ServiceRequestID");


--
-- Name: IX_Documents_ServiceRequestID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Documents_ServiceRequestID" ON public."Documents" USING btree ("ServiceRequestID");


--
-- Name: IX_Invoices_ServiceRequestID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Invoices_ServiceRequestID" ON public."Invoices" USING btree ("ServiceRequestID");


--
-- Name: IX_Payments_InvoiceID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Payments_InvoiceID" ON public."Payments" USING btree ("InvoiceID");


--
-- Name: IX_Schedules_ServiceRequestID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Schedules_ServiceRequestID" ON public."Schedules" USING btree ("ServiceRequestID");


--
-- Name: IX_ServiceRequests_CreatedByUserID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ServiceRequests_CreatedByUserID" ON public."ServiceRequests" USING btree ("CreatedByUserID");


--
-- Name: IX_ServiceRequests_VesselID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ServiceRequests_VesselID" ON public."ServiceRequests" USING btree ("VesselID");


--
-- Name: Cargos FK_Cargos_ServiceRequests_ServiceRequestID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cargos"
    ADD CONSTRAINT "FK_Cargos_ServiceRequests_ServiceRequestID" FOREIGN KEY ("ServiceRequestID") REFERENCES public."ServiceRequests"("RequestID") ON DELETE CASCADE;


--
-- Name: Documents FK_Documents_ServiceRequests_ServiceRequestID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Documents"
    ADD CONSTRAINT "FK_Documents_ServiceRequests_ServiceRequestID" FOREIGN KEY ("ServiceRequestID") REFERENCES public."ServiceRequests"("RequestID") ON DELETE CASCADE;


--
-- Name: Invoices FK_Invoices_ServiceRequests_ServiceRequestID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invoices"
    ADD CONSTRAINT "FK_Invoices_ServiceRequests_ServiceRequestID" FOREIGN KEY ("ServiceRequestID") REFERENCES public."ServiceRequests"("RequestID") ON DELETE CASCADE;


--
-- Name: Payments FK_Payments_Invoices_InvoiceID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Payments"
    ADD CONSTRAINT "FK_Payments_Invoices_InvoiceID" FOREIGN KEY ("InvoiceID") REFERENCES public."Invoices"("InvoiceID") ON DELETE CASCADE;


--
-- Name: Schedules FK_Schedules_ServiceRequests_ServiceRequestID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Schedules"
    ADD CONSTRAINT "FK_Schedules_ServiceRequests_ServiceRequestID" FOREIGN KEY ("ServiceRequestID") REFERENCES public."ServiceRequests"("RequestID") ON DELETE CASCADE;


--
-- Name: ServiceRequests FK_ServiceRequests_Users_CreatedByUserID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ServiceRequests"
    ADD CONSTRAINT "FK_ServiceRequests_Users_CreatedByUserID" FOREIGN KEY ("CreatedByUserID") REFERENCES public."Users"("UserID") ON DELETE CASCADE;


--
-- Name: ServiceRequests FK_ServiceRequests_Vessels_VesselID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ServiceRequests"
    ADD CONSTRAINT "FK_ServiceRequests_Vessels_VesselID" FOREIGN KEY ("VesselID") REFERENCES public."Vessels"("VesselID") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 5Ybf6SkUZOAsWXuUrgrXQLfipQZG59HXri3OHnyopQ2BoNfVenqM9jTJpGxOe3T

